### ISSUE TITLE
Trouble getting this working with CodeIgniter on PHPStorm 7.1

### ISSUE THREAD

**Issue by timothyjlaurent** [topdown/phpStorm-CC-Helpers#6]
I have added my models to my_models. I have imported Them into the project root and I have included their paths in the php include, I have tried both plain text and php files. 
![image](https://f.cloud.github.com/assets/2000204/2115862/b8a8f4d2-905c-11e3-9469-3212c4a5380e.png)

Still I get no code completion:
![image](https://f.cloud.github.com/assets/2000204/2115869/083e7bf2-905d-11e3-8c55-a7c6b2bc0f00.png)

Also no active record:

  
![image](https://f.cloud.github.com/assets/2000204/2115874/29bff79c-905d-11e3-8262-59892c2dc214.png)

Any thought on why this won't work ?? anything else I can try?

BTW I have also Invalidated Caches and restarted.

Thanks,

**Comment by topdown** [comment]
This issue is pretty stale. Feel free to create a new one if needed.
