### ISSUE TITLE
Cannot make it work in PHPStorm 8.0.2

### ISSUE THREAD

**Issue by taiar** [topdown/phpStorm-CC-Helpers#7]
Hello guys,

I'm new to PHPStorm and I'm still adapting on this IDE. However, I tried all the ways in documentation to make Codeigniter completion to work in a ongoing project with Codeigniter and PHPStorm 8.0.2 and I got no success.

Has anyone already succeeded on that? Please, let me know!

Thanks!

**Comment by topdown** [comment]
What version of CI?

Thanks
Jeff

**Comment by taiar** [comment]
@topdown 2.2.0

Thank you!

**Comment by topdown** [comment]
It should work fine with that version.
Try invalidating caches. 
In phpStorm click file in the top menu, in the dropdown there should be an Invalidate Caches / Restart

If that does not work, let me know what you are working on that is not working, so I can test.

**Comment by ROunofF** [comment]
I confirm I'm using PHPStorm 8.0.2 and I have no issue... Did you correctly "Mark as plain text" the files in the regular project (now the one coming with cc-helpers)

**Comment by taiar** [comment]
Thank you for your feedback guys. I recorded a video so you can check better (if you could) of what am I missing (sorry for the soundtrack).

https://www.youtube.com/watch?v=adnClM6h7vs

Thanks so much for all the support! :thumbsup:

**Comment by androsfat** [comment]
Mark only as plain text:
'system/core/Controller.php'
'system/core/Model.php'

Replace with your custom models all examples in
'application/models/my_models.php'

It should work

**Comment by taiar** [comment]
@androsfat No. It doesn't. :cry:

**Comment by topdown** [comment]
CI needs to be running within the PHP path for this to work. Eg. XAMPP
Then the PHP paths need to be correct in phpStorm. (It may detect them)
From the video it looks like your just using your desktop. Put it under XAMPP in the htdocs with a new project name.

**Comment by androsfat** [comment]
Try capitalising first letter of your models i.e.

$this->Side_mode->

**Comment by taiar** [comment]
Thank you guys.
I was able to make it work after @topdown tip to set the correct paths and the php interpreter too.
Many thanks for the help (everyone in the thread) and the good job in the package.

Cheers!
